language: node_js
node_js:
- '6'
env:
  - TEST_DIR=client
before_install:
  - npm install -g codecov.io coveralls
script:
  - cd $TEST_DIR
cache:
  directories:
    - node_modules
script:
  - npm i && npm i
  - npm run build:test
  - npm run test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
